zsh-z.plugin.zsh(1)
===================
:compat-mode!:

NAME
----
zsh-z.plugin.zsh - a shell script

SYNOPSIS
--------

ZSH-z - jump around with ZSH - A native ZSH version of z without awk, sort,
date, or sed

https://github.com/agkozak/zsh-z


FUNCTIONS
---------

 zshz
 _zshz_common
 _zshz_legacy_complete
 _zshz_output
 _zshz_update_datafile
 _zshz_usage
AUTOLOAD add-zsh-hook
AUTOLOAD is-at-least
CHPWD-HOOK _zshz_chpwd
PRECMD-HOOK _zshz_precmd

ENVIRONMENT VARIABLES
---------------------
[width="80%",cols="4,10"]
|======
|ZSHZ_CMD|name of command (default: z)
|ZSHZ_COMPLETION|completion method (default: 'frecent'; 'legacy' for alphabetic sorting)
|ZSHZ_DATA|name of datafile (default: ~/.z)
|ZSHZ_EXCLUDE_DIRS|array of directories to exclude from your database
|ZSHZ_NO_RESOLVE_SYMLINKS|'1' prevents symlink resolution
|ZSHZ_OWNER|your username (if you want use ZSH-z while using sudo -s) 
|======

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 27 line(s). Calls functions:

 Script-Body
 |-- add-zsh-hook
 `-- is-at-least

Uses feature(s): _alias_, _autoload_, _zmodload_

zshz
~~~~

____
 
 The ZSH-z Command
 
 Arguments:
 $* The command line arguments
____

Has 188 line(s). Calls functions:

 zshz
 |-- _zshz_legacy_complete
 |-- _zshz_output
 |   `-- _zshz_common
 `-- _zshz_update_datafile

Uses feature(s): _read_, _zparseopts_

Called by:

 _zshz_precmd

_zshz_chpwd
~~~~~~~~~~~

____
 
 When the $PWD is removed from the datafile with z -x,
 ZSH-z refrains from adding it again until the user has
 left the directory.
____

Has 1 line(s). *Is a chpwd hook*. Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_zshz_common
~~~~~~~~~~~~

____
 
 If matches share a common root, find it, and put it on the
 editing buffer stack for _zshz_output to use.
 
 Arguments:
 $1 Name of associative array of matches and ranks
____

Has 19 line(s). Doesn't call other functions.

Called by:

 _zshz_output

_zshz_legacy_complete
~~~~~~~~~~~~~~~~~~~~~

____
 
 The original tab completion method
 
 Process a string for tab completion. Read the contents of
 the datafile and print matches to STDOUT.
 
 Arguments:
 $1 The string to be completed
____

Has 23 line(s). Doesn't call other functions.

Called by:

 zshz

_zshz_output
~~~~~~~~~~~~

____
 
 Fetch the common root path from the editing buffer stack.
 Then either
 
 1) Print a list of completions in frecent order;
 2) List them (z -l) to STDOUT; or
 3) Put a common root or best match onto the editing
 buffer stack.
 
 Arguments:
 $1 Name of an associative array of matches and ranks
 $2 The best match or best case-insensitive match
 $3 Whether or not to just print the results as a
 list (0 or 1)
____

Has 39 line(s). Calls functions:

 _zshz_output
 `-- _zshz_common

Uses feature(s): _read_

Called by:

 zshz

_zshz_precmd
~~~~~~~~~~~~

____
 
 Add the $PWD to the datafile, unless $ZSHZ_REMOVED shows it to have been
 recently removed with z -x
   
____

Has 4 line(s). *Is a precmd hook*. Calls functions:

 _zshz_precmd
 `-- zshz
     |-- _zshz_legacy_complete
     |-- _zshz_output
     |   `-- _zshz_common
     `-- _zshz_update_datafile

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_zshz_update_datafile
~~~~~~~~~~~~~~~~~~~~~

____
 
 Read the curent datafile contents, update them, "age" them
 when the total rank gets high enough, and print the new
 contents to STDOUT.
 
 Arguments:
 $1 Path to be added to datafile
____

Has 41 line(s). Doesn't call other functions.

Called by:

 zshz

_zshz_usage
~~~~~~~~~~~

____
 
 The help message
____

Has 12 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

add-zsh-hook
~~~~~~~~~~~~

Has 93 line(s). Doesn't call other functions.

Uses feature(s): _autoload_, _getopts_

Called by:

 Script-Body

is-at-least
~~~~~~~~~~~

Has 56 line(s). Doesn't call other functions.

Called by:

 Script-Body

