zsh-z.plugin.zsh(1)
===================
:compat-mode!:

NAME
----
zsh-z.plugin.zsh - a shell script

SYNOPSIS
--------

ZSH-z - jump around with ZSH - A native ZSH version of z without awk, sort,
date, or sed

https://github.com/agkozak/zsh-z


FUNCTIONS
---------

 zshz
 _zshz_add_path
 _zshz_find_common_root
 _zshz_find_matches
 _zshz_legacy_complete
 _zshz_output
 zsh-z_plugin_unload
 _zshz_remove_path
 _zshz_update_datafile
 _zshz_usage
AUTOLOAD add-zsh-hook
AUTOLOAD is-at-least
CHPWD-HOOK _zshz_chpwd
PRECMD-HOOK _zshz_precmd

ENVIRONMENT VARIABLES
---------------------
[width="80%",cols="4,10"]
|======
|ZSHZ_CMD|name of command (default: z)
|ZSHZ_COMPLETION|completion method (default: 'frecent'; 'legacy' for alphabetic sorting)
|ZSHZ_DATA|name of datafile (default: ~/.z)
|ZSHZ_EXCLUDE_DIRS|array of directories to exclude from your database
|ZSHZ_MAX_SCORE|maximum combined score the database entries can have before beginning to age (default: 9000)
|ZSHZ_NO_RESOLVE_SYMLINKS|'1' prevents symlink resolution
|ZSHZ_OWNER|your username (if you want use ZSH-z while using sudo -s) 
|======

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 53 line(s). Calls functions:

 Script-Body
 |-- add-zsh-hook
 `-- is-at-least

Uses feature(s): _add-zsh-hook_, _alias_, _autoload_, _is-at-least_, _zmodload_

zshz
~~~~

____
 
 The ZSH-z Command
 
 Arguments:
 $* Command options and arguments
____

Has 103 line(s). Calls functions:

 zshz
 |-- _zshz_add_path
 |   `-- _zshz_update_datafile
 |-- _zshz_find_matches
 |   `-- _zshz_output
 |       `-- _zshz_find_common_root
 |-- _zshz_legacy_complete
 |-- _zshz_remove_path
 `-- _zshz_usage

Uses feature(s): _read_, _setopt_, _zparseopts_

Called by:

 _zshz_precmd

_zshz_add_path
~~~~~~~~~~~~~~

____
 
 Add a path to the datafile
 
 Arguments:
 $1 Path to be added
____

Has 42 line(s). Calls functions:

 _zshz_add_path
 `-- _zshz_update_datafile

Called by:

 zshz

_zshz_chpwd
~~~~~~~~~~~

____
 
 When the $PWD is removed from the datafile with z -x,
 ZSH-z refrains from adding it again until the user has
 left the directory.
____

Has 1 line(s). *Is a chpwd hook*. Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_zshz_find_common_root
~~~~~~~~~~~~~~~~~~~~~~

____
 
 If matches share a common root, find it, and put it on the
 editing buffer stack for _zshz_output to use.
 
 Arguments:
 $1 Name of associative array of matches and ranks
____

Has 18 line(s). Doesn't call other functions.

Called by:

 _zshz_output

_zshz_find_matches
~~~~~~~~~~~~~~~~~~

____
 
 Load the datafile, and match a pattern by rank, time, or a
 combination of the two, and output the results as
 completions, a list, or a best match.
 
 Arguments:
 #1 Pattern to match
 $2 Matching method (rank, time, or [default] frecency)
 $3 Output format (completion, list, or [default] print
 to editing buffer stack)
____

Has 58 line(s). Calls functions:

 _zshz_find_matches
 `-- _zshz_output
     `-- _zshz_find_common_root

Uses feature(s): _setopt_

Called by:

 zshz

_zshz_legacy_complete
~~~~~~~~~~~~~~~~~~~~~

____
 
 The original tab completion method
 
 String processing is smartcase -- case-insensitive if the
 search string is lowercase, case-sensitive if there are
 any uppercase letters. Spaces in the search string are
 treated as *'s in globbing. Read the contents of the
 datafile and print matches to STDOUT.
 
 Arguments:
 $1 The string to be completed
____

Has 19 line(s). Doesn't call other functions.

Uses feature(s): _setopt_

Called by:

 zshz

_zshz_output
~~~~~~~~~~~~

____
 
 Fetch the common root path from the editing buffer stack.
 Then either
 
 1) Print a list of completions in frecent order;
 2) List them (z -l) to STDOUT; or
 3) Put a common root or best match onto the editing
 buffer stack.
 
 Arguments:
 $1 Name of an associative array of matches and ranks
 $2 The best match or best case-insensitive match
 $3 Whether to produce a completion, a list, or a root or
 match
____

Has 48 line(s). Calls functions:

 _zshz_output
 `-- _zshz_find_common_root

Uses feature(s): _read_, _setopt_

Called by:

 _zshz_find_matches

zsh-z_plugin_unload
~~~~~~~~~~~~~~~~~~~

____
 
 Unload function
 
 See https://github.com/zdharma/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#unload-fun
____

Has 18 line(s). Calls functions:

 zsh-z_plugin_unload
 `-- add-zsh-hook

Uses feature(s): _add-zsh-hook_, _alias_, _unalias_, _unfunction_

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_zshz_precmd
~~~~~~~~~~~~

____
 
 Add the $PWD to the datafile, unless $ZSHZ[directory removed] shows it to have been
 recently removed with z -x
   
____

Has 4 line(s). *Is a precmd hook*. Calls functions:

 _zshz_precmd
 `-- zshz
     |-- _zshz_add_path
     |   `-- _zshz_update_datafile
     |-- _zshz_find_matches
     |   `-- _zshz_output
     |       `-- _zshz_find_common_root
     |-- _zshz_legacy_complete
     |-- _zshz_remove_path
     `-- _zshz_usage

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_zshz_remove_path
~~~~~~~~~~~~~~~~~

____
 
 Remove path from datafile
 
 Arguments:
 $1 Path to be removed
____

Has 29 line(s). Doesn't call other functions.

Uses feature(s): _setopt_

Called by:

 zshz

_zshz_update_datafile
~~~~~~~~~~~~~~~~~~~~~

____
 
 Read the curent datafile contents, update them, "age" them
 when the total rank gets high enough, and print the new
 contents to STDOUT.
 
 Arguments:
 $1 Path to be added to datafile
____

Has 40 line(s). Doesn't call other functions.

Called by:

 _zshz_add_path

_zshz_usage
~~~~~~~~~~~

____
 
 The help message
____

Has 12 line(s). Doesn't call other functions.

Called by:

 zshz

add-zsh-hook
~~~~~~~~~~~~

____
 
 Add to HOOK the given FUNCTION.
 HOOK is one of chpwd, precmd, preexec, periodic, zshaddhistory,
 zshexit, zsh_directory_name (the _functions subscript is not required).
 
 With -d, remove the function from the hook instead; delete the hook
 variable if it is empty.
 
 -D behaves like -d, but pattern characters are active in the
 function name, so any matching function will be deleted from the hook.
 
____

Has 93 line(s). Doesn't call other functions.

Uses feature(s): _autoload_, _getopts_

Called by:

 Script-Body
 zsh-z_plugin_unload

is-at-least
~~~~~~~~~~~

____
 
 
 Test whether $ZSH_VERSION (or some value of your choice, if a second argument
 is provided) is greater than or equal to x.y.z-r (in argument one). In fact,
 it'll accept any dot/dash-separated string of numbers as its second argument
 and compare it to the dot/dash-separated first argument. Leading non-number
 parts of a segment (such as the "zefram" in 3.1.2-zefram4) are not considered
 when the comparison is done; only the numbers matter. Any left-out segments
 in the first argument that are present in the version string compared are
 considered as zeroes, eg 3 == 3.0 == 3.0.0 == 3.0.0.0 and so on.
 
____

Has 56 line(s). Doesn't call other functions.

Called by:

 Script-Body

