#!/usr/bin/env zsh

# Generate Zshelldoc files for ZSH-z

zsd \
  --cignore '(\#*vim:*|\#\#*)' \
	--scomm \
    zsh-z.plugin.zsh

zsd \
  --cignore '(\#*vim:*|\#\#*)' \
  --scomm \
    _zshz

# vim: ts=2:sts=2:sw=2:et
