#!/usr/bin/env zsh

zsd \
  --cignore '(\#*vim:*|\#\#*)' \
	--scomm \
  --synopsis 'Plugin script for ZSH-z (https://github.com/agkozak/zsh-z)' \
    zsh-z.plugin.zsh

zsd \
  --cignore '(\#*vim:*|\#\#*)' \
  --scomm \
  --synopsis 'Completion script for ZSH-z (https://github.com/agkozak/zsh-z)' \
    _zshz

# vim: ts=2:sts=2:sw=2:et
